objects/VonageMessagingConversation__c.object
<CustomObject>
    <description>MessagingConversation groups MessagingHistory</description>
    <fields>
        <fullName>BrandPhoneNumber__c</fullName>
        <label>BrandPhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sms</fullName>
                    <default>true</default>
                    <label>sms</label>
                </value>
                <value>
                    <fullName>whatsapp</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactPhoneNumber__c</fullName>
        <label>ContactPhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>DateTimeCreated__c</fullName>
        <description>date time creation of conversation</description>
        <label>DateTimeCreated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastMessageDirection__c</fullName>
        <label>LastMessageDirection</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>out,in</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open,Closed,Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isUnread__c</fullName>
        <defaultValue>false</defaultValue>
        <description>marks conversation as unread</description>
        <label>isUnread</label>
        <type>Checkbox</type>
    </fields>
    <label>MessagingConversation</label>
    <nameField>
        <label>MessagingConversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MessagingConversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/VonageMessagingHistory__c.object
<CustomObject>
    <description>MessagingHistory</description>
    <fields>
        <fullName>BrandPhoneNumber__c</fullName>
        <description>BrandPhoneNumber</description>
        <label>BrandPhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>sms or whatsapp</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>sms</fullName>
                </value>
                <value>
                    <fullName>whatsapp</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactPhoneNumber__c</fullName>
        <description>Contact phone number</description>
        <label>ContactPhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>body of the message</description>
        <label>Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>out</fullName>
                </value>
                <value>
                    <fullName>in</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastMessageState__c</fullName>
        <description>LastMessageState : Submitted, Delivered, Read</description>
        <label>LastMessageState</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessagingConversation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>MessagingConversation</description>
        <label>MessagingConversation</label>
        <referenceTo>VonageMessagingConversation__c</referenceTo>
        <relationshipLabel>MessagingHistory</relationshipLabel>
        <relationshipName>MessagingHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MessagingHistory</label>
    <nameField>
        <label>MessagingHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MessagingHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/VonageMessagingUpdateEvent__e.object
<CustomObject>
    <description>VonageMessagingUpdateEvent
triggered when a message status is updated or a new inbound message is received.</description>
    <fields>
        <fullName>VonageMessagingConversationId__c</fullName>
        <description>VonageMessagingConversationId</description>
        <label>VonageMessagingConversationId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>VonageMessagingUpdateEvent</label>
    <pluralLabel>VonageMessagingUpdateEvents</pluralLabel>
</CustomObject>

classes/VonageMessaging.cls
public with sharing class VonageMessaging {
    
    //Method to return list of VonageMessagingHistory__c records during component initialization
    @AuraEnabled
    public static List<VonageMessagingHistory__c> loadData(String ObjectType,String ObjectId){
        String SQLReq = 'SELECT ID,Date_Time__c,Content__c,Direction__c,Channel__c,createdBy.Name,LastMessageState__c FROM VonageMessagingHistory__c WHERE MessagingConversation__r.'+ObjectType+'__c=\''+ObjectId+'\' ORDER BY Date_Time__c DESC NULLS LAST';
        System.debug('List MessageHistory - SQLReq='+SQLReq);
        return Database.query(SQLReq);
    }
    
    //Method to return details over VonageMessagingConversation record during component initialization
    @AuraEnabled
    public static List< VonageMessagingConversation__c > getConversationDataAPEX(String ObjectType,String ObjectId){
        String SQLReq = 'SELECT BrandPhoneNumber__c,ContactPhoneNumber__c,DateTimeCreated__c,isUnread__c,LastMessageDirection__c,State__c,Channel__c FROM VonageMessagingConversation__c WHERE '+ObjectType+'__c=\''+ObjectId+'\' LIMIT 1';
        System.debug('List Messageconversation - SQLReq='+SQLReq);
        return Database.query(SQLReq);
    }
    
    //Method to save the record in database and return error message
    @AuraEnabled
    public static String saveMessagingHistoryRecord(VonageMessagingHistory__c MessagingHistoryRecord){
        String message;
        Database.saveResult sr = Database.insert(MessagingHistoryRecord,false);
        if(!sr.isSuccess()){
            for(Database.error err : sr.getErrors()){
                message += err.getMessage();
            }
        }
        return message;
    }
    
    //Method to send Message via Vonage
    @AuraEnabled
    public static String sendMessagingHistory(String msgTo, String msgFrom, String channel, String text) {        
    
        String result = VonageAPIMessaging.sendMessage(msgTo, msgFrom, text, channel); 
        return result;

    }  
    
    //Method to trigger VonageMessagingUpdateEvent__e event and update Lightning component
     public static void fireVMUpdateEvent(String VMConversationId) {        
    
        VonageMessagingUpdateEvent__e VMMsgUpdate = new VonageMessagingUpdateEvent__e(
        VonageMessagingConversationId__c = 'test Event');
        EventBus.publish(VMMsgUpdate);  
     }   
}